name: Update LeetCode Stats

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    paths:
      - 'README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch LeetCode Stats
        id: leetcode
        uses: yanagi0306/leetcode-stats@v1.2.7
        with:
          username: dar00

      - name: Update README
        run: |
          leetcode_stats=$(cat $GITHUB_WORKSPACE/leetcode.stats.json)
          echo "Updating README with LeetCode stats"
          sed -i "s|<!-- LEETCODE_STATS -->|$leetcode_stats|g" README.md

      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update LeetCode stats'
          git push
